/*


Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


*/



#include <iostream>
using namespace std;

int main () {

    int cur = 1;
    int prev = 0;
    int prev1 = 0;
    int sum = 0;

    while (cur < 4000000) {
        
        if (cur % 2 == 0) {
            sum = sum + cur;
        }

        prev1 = prev;
        prev = cur;

        cur = prev + prev1;
    }

    cout << sum << endl;
        
}